### ISSUE TITLE
warning on invalid exif data

### ISSUE THREAD

**Issue by eroux** [buda-base/asset-manager#126]
Another feature related to the exif data. Some exif data in our images (in that case not legacy ones, they were synced yesterday) is invalid:

```sh
$ curl https://iiif.bdrc.io/bdr:I8LS26144::I8LS261440003.jpg/full/full/0/default.jpg -o full.jpg
$ exiftool full.jpg |grep Warning
Warning                         : IFD1 pointer references previous ExifIFD directory
```

This makes the thumbnail impossible to extract by exiftool, and I think is a probable cause of the iiif server not reacting well when trying to extract the icc profile.

**Comment by jimk-bdrc** [comment]
@TBRC-Travis Please find out the source of this image.

**Comment by TBRC-Travis** [comment]
This is from W8LS20439 which I synced from the Mangaram backlog

**Comment by jimk-bdrc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Why we need a platform](https://trello.com/c/KNxLZ8qc/23-why-we-need-a-platform)

**Comment by eroux** [comment]
to give a bit more context: the iiif server is happy with this image and so are the web browsers so it's fine. I encountered this issue while trying to extract the jpg thumbnail from the image with exiftool (to measure its size I think), but it's not at all a common usage of our images so I think we can live with it. I also can't reproduce this issue in Java
