### ISSUE TITLE
Add support for version flag to audittool

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/asset-manager#134]
How do you know which version of audittool you're running?  Right now on Linux you have to run the following to know which version you're running: `update-alternatives --display audittool.sh `

On Macs it's not all that clear how to determine the version you're running.

For the next release of audittool it would be great to add a `--version` flag to make it easy to determine the version you're running.

**Comment by jimk-bdrc** [comment]
Not only display, but log.

**Comment by jimk-bdrc** [comment]
https://itaffinity.wordpress.com/2014/02/25/maven-create-a-simple-build-number/

**Comment by jimk-bdrc** [comment]
Clsed in PR #153
