### ISSUE TITLE
Test Audit Tool 1.0-alpha Functionality

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/asset-manager#146]
Test the functionality on the new install

Release documentation is [Here in Github](https://github.com/buda-base/asset-manager/releases/tag/v1.0-alpha). It has the link to the online documentation.

- run without arguments
- run with -help
- run with files on stdin. (cat bla | audit-tool  - )
- run on file input (audit-tool -i)
- run on list of directoried (audit-tool d1, d2 ,d3)
- validate a changed parameter in user.properties takes effect
- validate a changed parameter in the global properties takes effect. This has two changes:
       - global shell.properties
       - override global and user properties in the JVM Config. These modes are shown in [Operation](https://buda-base.github.io/asset-manager/user/AuditTool/AuditToolOperation-1.0/)

**Comment by jimk-bdrc** [comment]
Verify which Java is native

Platform Type|Host|Assignee
---|---|---
MacOS|Druk|@jimk-bdrc
&nbsp;|Khyung|@TBRC-Timb
&nbsp;|Windhorse|@TBRC-Travis
Debian|AWS_AO|@jimk-bdrc
&nbsp;|sattva|@TBRC-Travis
Windows|CANTH|@jimk-bdrc
&nsbp;|bodhi virtualbox|@jimk-bdrc

**Comment by TBRC-TimB** [comment]
@jimk-bdrc were you going to post a link to the installation documentation here? I went looking but couldnt find anything that looked correct.

**Comment by jimk-bdrc** [comment]
> were you going to post a link to the installation documentation here? I went looking but couldnt find anything that looked correct.

Thanks - I put links to the release in the issue description and in #147.  
The release has a link to the GitHub pages documentation.

**Comment by TBRC-TimB** [comment]
So reporting back after my first pass at trying this out. 
On windows
- [ ] install
- [ ] add to path
- [ ] run empty
- [ ] run with -help flag
- [ ] run on stdin
- [ ] run with a file input ( -i )
- [ ] run with a list of dirs
- [ ] run on -i
- [ ] change user.properties 
- [ ] change global properties

It seems the .config dir wasnt generated during install, but that might have been an admin problem on my end. Im going to keep fiddling with it. 
As for Khyung
As far as I can tell installing from the .dmg file didn't prompt me to upgrade or install over the existing version of audittool on that machine. Calling it from the command line just called the older version (i have some outdated testing configs on that one.) Not sure if I messed up the installation, but its hard to screw up drag and drop.

**Comment by jimk-bdrc** [comment]
> It seems the .config dir wasnt generated during install, but that might have been an admin problem on my end. Im going to keep fiddling with it.
Where do you see that the ~/.config folder was generated during install.

> Calling it from the command line just called the older version
Can you please post the command line?

**Comment by TBRC-TimB** [comment]
for the khyung calls: 
```
audittool.sh W2KG209840
starting W2KG209840
INFO  Passed	/Users/timb/staging/W2KG209840		No Files in Root Folder
ERROR Failed	/Users/timb/staging/W2KG209840		Web Image Attributes
INFO  Passed	/Users/timb/staging/W2KG209840		No folders allowed in Image Group folders
ERROR Failed	/Users/timb/staging/W2KG209840		File Sequence Test
Errors! returned:1: check logs
```

as for the .config file. That was where in the documentation it said I would find `user.properties` I went looking for that directory and it wasnt at my home level  `C:\Users\timdb`

**Comment by TBRC-TimB** [comment]
I'm thinking now there is probably a way to evoke the new audittool from the applications dir on khyung. I'll go back to digging around.

**Comment by jimk-bdrc** [comment]
Yes, it's an all new executable. Should be covered in the doc

**Comment by jimk-bdrc** [comment]
But is wasn't!    Doc Bug:
![image](https://user-images.githubusercontent.com/33470789/152422228-a595791e-32bf-4381-a294-dd257d4688f7.png)

**Comment by jimk-bdrc** [comment]
Fixed doc bug
![image](https://user-images.githubusercontent.com/33470789/152423346-1516eb24-1e55-4063-a587-3c1a5c3ba3e8.png)

**Comment by TBRC-TimB** [comment]
ok now that I got it all set up on khyung and added to the path it worked like a charm. Looks like it worked out for my two tests.

**Comment by TBRC-Travis** [comment]
@jimk-bdrc I successfully installed the deb package on sattva:

```
travis@sattva:~/downloads$ sudo dpkg -i Debian.audit-v1_1.0-alpha-1_amd64.deb 
Selecting previously unselected package audit-v1.
(Reading database ... 163134 files and directories currently installed.)
Preparing to unpack Debian.audit-v1_1.0-alpha-1_amd64.deb ...
Unpacking audit-v1 (1.0-alpha-1) ...
Setting up audit-v1 (1.0-alpha-1) ...
```

But I'm not sure where it gets installed.  Need the installation path on Linux to setup my PATH to point to it.

**Comment by TBRC-Travis** [comment]
Got it.  dpkg --contents Debian.audit-v1_1.0-alpha-1_amd64.deb points me to `/opt/audit-v1/`

**Comment by TBRC-Travis** [comment]
Test on sattva:

- [] install
- [] add to path
- [] run empty
- [] run with -help flag
- [] run on stdin
- [] run with a file input ( -i )
- [] run with a list of dirs
- [] run on -i
- [ ] change user.properties 
- [] change global properties

**Comment by TBRC-Travis** [comment]
Failed -help (and --help) on sattva:

```
travis@sattva:~$ audit-tool -help
ERROR Failed to parse Unrecognized option: -help
usage: audit-tool [options] { - | Directory,Directory,Directory}
where:

                  - read folders from standard input

                  Directory .... is a list of directories separated by
                  whitespace
[options] are:
 -d,--debug             Show debugging information
 -i,--inputFile <arg>   Input file, one path per line
 -l,--log_home <arg>    Test Result log directory. Must be writable.
                        Default is <UserHome>/audit-test-logs/. Created if
                        not exists
Exiting on exception Cannot invoke "org.apache.commons.cli.CommandLine.hasOption(String)" because "this.cl" is null
ERROR java.lang.NullPointerException: Cannot invoke "org.apache.commons.cli.CommandLine.hasOption(String)" because "this.cl" is null
```

**Comment by jimk-bdrc** [comment]
> Got it. `dpkg --contents Debian.audit-v1_1.0-alpha-1_amd64.deb` points me to `/opt/audit-v1/`

Super! I'll add that to the documentation. I didn't know about `dpkg --contents`

**Comment by jimk-bdrc** [comment]
> I successfully installed the deb package on sattva:
Was that how the documentation said to install it?

**Comment by TBRC-Travis** [comment]
I saw the result from your test _"Not installable - Not an apt platform_" for your Debian installation and (wrongly) assumed that `apt` wasn't available on sattva either (turns out it is).  `apt` calls `dpkg` to do the installation anyway so the end result in this case is the same.  

but now that I'm looking more closely at installers we may be able to combine the download/installation steps into one using `apt-get` which could be a neat improvement.

**Comment by TBRC-Travis** [comment]
I might suggest changing the install location from `/opt/audit-v1` to `/opt/audit-tool `so the directory isn't tied to a version number (screwing up `PATH` designations for future versions, for example)

**Comment by TBRC-Travis** [comment]
@jimk-bdrc I'm not sure I understand the usage of input files in the context of audittool and the documentation isn't explicit.  What's the use case for the  `-i,--inputFile <arg>`  flag?  Is it to pass in alternative config files?

**Comment by jimk-bdrc** [comment]
> I might suggest changing the install location from `/opt/audit-v1` to `/opt/audit-tool `so the directory isn't tied to a version number (screwing up `PATH` designations for future versions, for example)

That's not standard Linux practice, as with many long running platforms, you have to have multiple versions side-by-side. The way I did it is also not so good.  The best practice would be to make the path `/opt/audit-tool/audit-tool-v1`

The Debian documentation has a discussion of how to use `update-alternatives` to be able to support side-by-side. When you use that, nobody has to change a path.

**Comment by jimk-bdrc** [comment]
> @jimk-bdrc I'm not sure I understand the usage of input files in the context of audittool and the documentation isn't explicit. What's the use case for the `-i,--inputFile <arg>` flag? Is it to pass in alternative config files?

I will clean up the help banner so this is clear. I used several different terms for "paths to work."
