### ISSUE TITLE
Test Audit tool installation

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/asset-manager#147]
Test on supported platforms:

Release documentation is [Here in Github](https://github.com/buda-base/asset-manager/releases/tag/v1.0-alpha). It has the link to the online documentation.

- Debian 10 (sattva)
- (for thrills - on Amazon Linux)
- Windows 10 (install on virtualbox on bodhi)
- MacOS

See #146 for test matrix

Test new install
Test re-install over existing
Test removal and re-install (change a parameter in global settings, see that it takes effect)

**Comment by jimk-bdrc** [comment]
Added link to release page in issue description.

**Comment by TBRC-TimB** [comment]
thanks Jim!

**Comment by jimk-bdrc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ongoing AO Meeting notes](https://trello.com/c/D5duhIin/18-ongoing-ao-meeting-notes)
