### ISSUE TITLE
Cant run the configuration command in Windows Powershell 

### ISSUE THREAD

**Issue by jeehuajian** [buda-base/asset-manager#54]
#### we try to run the configuration command in PowerShell but not able to run the command.

![002](https://user-images.githubusercontent.com/42564256/73524285-c3689800-4447-11ea-8c9c-627078d6894f.PNG)

## 2)  Window System Information

![004](https://user-images.githubusercontent.com/42564256/73524408-09256080-4448-11ea-8e6d-451c0dff1fb2.PNG)

**Comment by TBRC-JimK** [comment]
What powershell version are you running? Before Powershell 6.0, executing of powershell scripts was restrcited. See [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy) on this issue.

**Comment by ngawangtrinley** [comment]
It wasn't a version issue. We've spent a day trying with Powershell 6.0 and above to no avail, the execution permissions have to be changed regardless of the version. We're creating tutorials for this in Chinese and Tibetan.
