### ISSUE TITLE
Detail log file without Web Image attributes details

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/asset-manager#64]
On a failed Wed image attribute, the DETAIL log file will not list out any failures at all. Just the headers for the columns. The DETAIL log will still list out failures for other tests (such as sequence breaks) but not for the web image attribute failures. 

*SUMMARY-2020-02-20-11-54*
outcome,path,test_name
Passed,/Users/timb/staging/QA-Review/W8LS31241,No Files in Root Folder
Failed,/Users/timb/staging/QA-Review/W8LS31241,Web Image Attributes
Passed,/Users/timb/staging/QA-Review/W8LS31241,No folders allowed in Image Group folders
Failed,/Users/timb/staging/QA-Review/W8LS31241,File Sequence Test

*DETAIL-2020-02-20-11-54*
error_number,error_test,path
109,"Folder /Users/timb/staging/QA-Review/W8LS31241/archive/W8LS31241-I8LS31246 expected 885 files in folder , found 883",/Users/timb/staging/QA-Review/W8LS31241
105,Sequence File Sequence    1 missing not found,/Users/timb/staging/QA-Review/W8LS31241
105,Sequence File Sequence    2 missing not found,/Users/timb/staging/QA-Review/W8LS31241

*SUMMARY-2020-02-20-10-23*
outcome,path,test_name
Passed,/Users/timb/staging/QA-Review/W8LS31064,No Files in Root Folder
Failed,/Users/timb/staging/QA-Review/W8LS31064,Web Image Attributes
Passed,/Users/timb/staging/QA-Review/W8LS31064,No folders allowed in Image Group folders
Passed,/Users/timb/staging/QA-Review/W8LS31064,File Sequence Test

*DETAIL-2020-02-20-10-23*
error_number,error_test,path

**Comment by TBRC-JimK** [comment]
The test outcome was a failure because the work had no 'images' folder (the value of `shell.properties` "DerivedImageGroupsParent" property.

The fix is to create a `TestResult` error, rather than having the test exit on an exception.
